### ISSUE TITLE
docs not rendering on the deployed platform

### ISSUE THREAD

**Issue by paoloantinori** [Apicurio/backstage#40]
you can check there. (but they are also not rendering on my local development system. I only see the first page, but if I click on `documentation-demo` I get an error page

**Comment by renjingxiao** [comment]
Hi @paoloantinori ,

I rebuilt it locally from scratch on my computer and the doc system seems to work fine on macOS. Could you please send me the error logs on your page, if you haven’t terminated it yet?

Additionally, I noticed that the version of `mkdocs-techdocs-core` should be 1.2.1 instead of 1.0.2 in Dockerfile. Could this be the source of the issue? If it's not, could you also provide me with the error logs from the deployment platform?

Thank you

**Comment by paoloantinori** [comment]
On my local environment, the issue was that I was not using the Virtual Env. I didn't have `mkdocs-techdocs-core` in my context.

Fixing that, things work locally, but they are still not working on our environments, as you can check.

We should download locally the Docker image, run it locally, and try to understand what's the issue

```podman pull quay.io/apicurio/backstage```

**Comment by paoloantinori** [comment]
@andreaTP anticipated this might break, here: https://github.com/Apicurio/backstage/issues/23

**Comment by renjingxiao** [comment]
Thank you for the information. I'll try that.

**Comment by andreaTP** [comment]
fixed in #46
